eds.measurement improvements
aphp/edsnlp pull request #299
Opened 2024-05-29 10:14 UTC by svittoz

## Description

- add **table processing** in eds.measurements
- add the possibility to extract **all measurements**
- update eds.measurements config to extract **more units**

## Checklist

- [ ] If this PR is a bug fix, the bug is documented in the test suite.
- [ ] Changes were documented in the changelog (pending section).
- [ ] If necessary, changes were made to the documentation (eg new pipeline).

2024-06-12 11:48 UTC, percevalw commented on edsnlp/pipes/misc/measurements/patterns.py
> +        "per": ["g-1", "gr-1", "gr⁻¹", "g⁻¹"],
```suggestion
        "per_terms": ["g-1", "gr-1", "gr⁻¹", "g⁻¹"],
```

2024-06-12 13:20 UTC, percevalw requested changes
Good work on the `use_tables` feature and the expansion of unit configuration!
However, I have mixed feelings about the way these new units are generated. On the one hand, there's a lot of redundancy (g -> kg, mg, cg, dc, etc), which suggests a factorisation of these prefixes. On the other hand, the devil is in the detail and there are many exceptions that require overriding these pre-generated units (cc for ‘cubic centimeter’, ‘d ui’ for deci ui) that have been forgotten in the course of these changes.

Replacing the unit terms after the large config doesn't help readability, so I'd be more in favour of wrapping the config individually and finding a way to place overrides near the base config, eg.

```python
    ...
    **generate_scaled_units(base_config, scale_prefixes, overrides)
```

```python
config.update(generate_scaled_units(base_config, scale_prefix))
config["cm3"]...
```

2024-06-12 13:37 UTC, percevalw commented on edsnlp/pipes/misc/measurements/patterns.py
> +            "scale": scale_value,
In the case of "liters", I believe this doesn't account for the fact that a liter is 1e-3 m3.
And while we have m3 -> 1, dm3 -> 1e-3, cm3 -> 1e-6, we have liter -> 1e-3, deciliter -> 1e-4, centiliter -> 1e-5.
Managing the scales is not easily done automatically...

2024-07-11 17:07 UTC, svittoz commented
> Good work on the `use_tables` feature and the expansion of unit configuration! However, I have mixed feelings about the way these new units are generated. On the one hand, there's a lot of redundancy (g -> kg, mg, cg, dc, etc), which suggests a factorisation of these prefixes. On the other hand, the devil is in the detail and there are many exceptions that require overriding these pre-generated units (cc for ‘cubic centimeter’, ‘d ui’ for deci ui) that have been forgotten in the course of these changes.
> 
> Replacing the unit terms after the large config doesn't help readability, so I'd be more in favour of wrapping the config individually and finding a way to place overrides near the base config, eg.
> 
> ```python
>     ...
>     **generate_scaled_units(base_config, scale_prefixes, overrides)
> ```
> 
> ```python
> config.update(generate_scaled_units(base_config, scale_prefix))
> config["cm3"]...
> ```

2024-07-19 16:22 UTC, merged