Force batch size of 2000 when distributing pipe
aphp/edsnlp pull request #73
Opened 2022-05-05 11:38 UTC by Thomzoy

Force batch size of 2000 when distributing pipe

## Description

We use the `repartition` method of `PySpark` to split data in partitions of roughly 2000 texts before applying the matcher's UDF.
This will improve performances by removing a common bottleneck of very skewed tasks.

## Checklist

- [x] If this PR is a bug fix, the bug is documented in the test suite.
- [x] Changes were documented in the changelog (pending section).
- [x] If necessary, changes were made to the documentation (eg new pipeline).

2022-05-06 16:06 UTC, bdura requested changes
Looks good! Can you modify the changelog (see suggestion)? Version 0.5.3 is already released...

2022-05-06 16:06 UTC, bdura commented on changelog.md
> +## Pending v0.5.3
```suggestion
## Pending Release
```

2022-05-24 07:53 UTC, Thomzoy commented
Forgot about this PR, should be good now !

2022-05-25 09:59 UTC, bdura approved these changes

2022-05-25 10:01 UTC, bdura commented
I took the liberty of merging upstream changes. Everything looks good to me!

2022-05-30 12:18 UTC, merged